//! Poseidon reference test vectors and MDS matrix verification.
//!
//! This file contains:
//! 1. Hardcoded reference test vectors for PoseidonGoldilocks::permute()
//!    covering zero state, single non-zero, all-ones, max field element,
//!    sequential, and random states (Task 3.1, Requirements 3.1, 3.2)
//! 2. MDS matrix non-singularity verification (Task 3.2, Requirement 3.4)
//! 3. Conformance tests comparing permute() output against every reference
//!    vector (Task 3.3, Requirement 3.5)

use vsel_crypto::goldilocks::GoldilocksField;
use vsel_crypto::poseidon_goldilocks::{PoseidonGoldilocks, STATE_WIDTH};

// ============================================================================
// Helpers
// ============================================================================

/// Helper: create a state from a slice of u64 values.
fn state_from(vals: &[u64; STATE_WIDTH]) -> [GoldilocksField; STATE_WIDTH] {
    let mut state = [GoldilocksField::ZERO; STATE_WIDTH];
    for i in 0..STATE_WIDTH {
        state[i] = GoldilocksField(vals[i]);
    }
    state
}

/// Helper: extract u64 values from a state.
fn state_to_u64(state: &[GoldilocksField; STATE_WIDTH]) -> [u64; STATE_WIDTH] {
    let mut vals = [0u64; STATE_WIDTH];
    for i in 0..STATE_WIDTH {
        vals[i] = state[i].0;
    }
    vals
}

// ============================================================================
// Task 3.1: Hardcoded Reference Test Vectors (Requirements 3.1, 3.2)
// ============================================================================
//
// Each vector is a (name, input, expected_output) triple for
// PoseidonGoldilocks::permute(). These were generated by running the
// PoseidonGoldilocks implementation (t=12, R_f=8, R_p=22, S-box x^7,
// Goldilocks field, NUMS round constants, Cauchy MDS matrix) and recording
// the outputs as hardcoded constants for regression testing.
//
// The vectors are frozen — any change to the Poseidon implementation that
// alters these outputs indicates a breaking change that must be investigated.

const P: u64 = GoldilocksField::MODULUS; // 0xFFFFFFFF00000001

/// Returns all 21 reference test vectors as (name, input, expected_output).
fn reference_vectors() -> Vec<(&'static str, [u64; 12], [u64; 12])> {
    vec![
        // --- Category 1: Zero state permutation ---
        (
            "zero_state",
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [17776268160436713992, 13484960287237122879, 8072290751062992204, 11580099673436387810, 10497940406619895323, 2228943300489664845, 17631245483957960459, 8588595693792710836, 594294450056788254, 5771626098660422165, 7799099188971467012, 4378146451967639013],
        ),
        // --- Category 2: Single non-zero element ---
        (
            "single_elem_0_is_1",
            [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [2834918530254927471, 3118718571921925844, 3839557628011740136, 18266699724177675773, 1215960798358789757, 2772284151986855561, 7395158406366961618, 3506228761177901032, 18321277178875189596, 7996100105831526738, 257405600219080062, 3525703918798009207],
        ),
        (
            "single_elem_0_is_42",
            [42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [10419309535127071262, 12227481227367914654, 10648628399307100907, 12142252666389489618, 4079335981572255086, 2008470402479927207, 5370696240816644940, 3124691407086253292, 14943379959235698596, 6126645534663759991, 3244966826699666205, 244014790502017422],
        ),
        (
            "single_elem_5_is_1",
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            [12020119550456412216, 1676381170289198344, 5682644411189321774, 3286742647796719811, 9824149698484117799, 5852331338269911876, 3976437881134586035, 1068445751553664080, 4839758372460474300, 9589418718054479096, 9386713390925388192, 6907874642914984989],
        ),
        (
            "single_elem_11_is_1",
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            [3638747864008464722, 5102182802409322601, 4823651942471644392, 15361551570797293578, 16164126970855765037, 18231142131845754696, 15240181307850751396, 12778622970646453012, 5202819522485760785, 10691108485640040805, 6999551619401346200, 11728329356213503960],
        ),
        // --- Category 3: All-ones state ---
        (
            "all_ones",
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [16876301287218863540, 10221470712347406754, 523441862593599623, 648224604478182890, 3685777650489960684, 6069221330454559794, 4230991806330459835, 8019351987677262943, 9493510694639742092, 13317897876414229300, 8822892940058747718, 18033018322883919080],
        ),
        // --- Category 4: Maximum field element state ---
        (
            "all_max",
            [P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1, P - 1],
            [3492001120930797373, 3341881054653038042, 4090369161410131700, 11000346046292789094, 16730027019263958247, 582892198737888034, 8071762114649879955, 15843383151331995084, 13636269320184716572, 1507585169200131264, 2291558161465885179, 13951554099820012272],
        ),
        // --- Category 5: Sequential element state ---
        (
            "sequential_1_to_12",
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            [12892740726097325063, 14167127426056658081, 7700123107614157417, 10757849109382854198, 17252383644978629106, 16922888036395890795, 9359359935593667672, 9173169540892869947, 13842781980261475212, 5401845114291372617, 9541507221602619704, 12253879164994411856],
        ),
        (
            "sequential_0_to_11",
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            [16860875041418476020, 323326226639050608, 9810376131784990050, 10342960473078324944, 16515859261865784538, 13050793295973942568, 1425942432459756575, 13196147009728906657, 15731933525445424719, 8073611977146477617, 9072623674556982413, 13013632959805128200],
        ),
        (
            "sequential_100_to_111",
            [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111],
            [14332050314429604168, 2969978382697983982, 1356164850490624954, 8692273455028279818, 13185046099762499709, 11528935390517517514, 15606622230063563028, 17936571950566635828, 16854411533656345021, 4344639933140103861, 5739293520321720459, 1390015863884586335],
        ),
        // --- Category 6: Random states with known outputs ---
        (
            "random_1",
            [3735928559, 3405691582, 305419896, 2596069104, 286331153, 572662306, 858993459, 1145324612, 1431655765, 1717986918, 2004318071, 2290649224],
            [10755360633507033562, 10348966304306760041, 3398301199186731712, 6922201653610697415, 981746654367767143, 14337101410480827019, 2437760570011537862, 6091710424485705359, 17174121204156427049, 2019092910364362982, 12835869035166646309, 16079499143507488444],
        ),
        (
            "random_2",
            [1000000007, 999999937, 999999893, 999999883, 999999877, 999999613, 999999607, 999999541, 999999527, 999999503, 999999491, 999999443],
            [11641271934839497294, 1590295713396507818, 13778207037728339920, 10442115088066342210, 3384792469069314404, 18263164624640397612, 3968922449812461801, 3032623318547536651, 3357435187926341277, 15837562479292062757, 661557530084660298, 15936375076105600718],
        ),
        (
            "random_3",
            [4294967295, 4294967296, 1, 18446744065119617026, 9223372034707292161, 2863311530, 1431655765, 3149642683, 3435973836, 3722304989, 4008636142, 2576980377],
            [3372092970663825524, 4949658166468372953, 7233265105576594090, 12751395499253437632, 1030222193042891492, 17895117115005137680, 16511983364593670610, 14824083666732152793, 6921283223310663529, 211907606533366892, 8241703938672876539, 13303334923103583412],
        ),
        (
            "random_4",
            [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37],
            [14284451563679004918, 4034076176364178842, 7586152066348105644, 8325643918001471416, 17431282002274772887, 17918018674615923844, 3872882929985968803, 15662244767309166339, 5612483086309302194, 10021355524703794227, 13687395012297754537, 1641537940025160927],
        ),
        (
            "random_5",
            [P - 1, 4294967295, 9223372036854775808, 9223372036854775807, 4294967296, 18446744065119617026, 8589934592, 18446744060824649731, 12884901888, 18446744056529682436, 17179869184, 18446744052234715141],
            [2320447283950103425, 1920571441355334729, 3392468583767516767, 8446886125033440936, 8597238799094018010, 3337188654622995882, 14276334610912798995, 15883278896916224458, 16151092989802673503, 430783467080208510, 1791630665447276335, 6123148667049118598],
        ),
        (
            "random_6",
            [42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42],
            [5731115736544134262, 15868773441133389842, 8819174299271706777, 14267316252032062988, 6739991327240295207, 6752138539375816684, 6740482152179407907, 18186152756764753585, 6259068217124904163, 7920989621628665192, 862511973923620438, 8024493058918971443],
        ),
        (
            "random_7",
            [P - 2, P - 3, P - 4, P - 5, P - 6, P - 7, P - 8, P - 9, P - 10, P - 11, P - 12, P - 13],
            [8795312330630174372, 16850718651546446586, 17419513427768474924, 9500301541717389293, 8764300811431743866, 9911353899956849634, 17110654446219674700, 2493968415101378293, 15736674007271216541, 1042907388987811339, 9114380410597176442, 8314644507335025894],
        ),
        (
            "powers_of_two",
            [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048],
            [6181431130362637256, 11555868207983669241, 2336547489314367266, 11734723578684748475, 11766985219845473947, 4197055001761600920, 16888341277270003076, 10579679055165776552, 13231749531528441173, 469298811966713947, 2210850992810663841, 9514160251113475012],
        ),
        (
            "fibonacci_like",
            [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144],
            [8825264016192915243, 12974190106962155479, 386555807913905974, 14977592124678959616, 6249035473285105814, 5564018510808645698, 17675125699915770964, 10222960401210233213, 4494172666373027332, 11428692516869814099, 16776357383658233645, 4822259899771678280],
        ),
        (
            "alternating_zero_max",
            [0, P - 1, 0, P - 1, 0, P - 1, 0, P - 1, 0, P - 1, 0, P - 1],
            [8287187200799483710, 4862396390857506790, 3646105111394549548, 2034460954091885296, 9634499582665912129, 16151891485557175014, 2625999211482145076, 7027220592303599517, 4637297929967569582, 1481136890275921384, 16041460961796324959, 8876320472991836864],
        ),
    ]
}

// ============================================================================
// Task 3.3: Conformance Tests Against Reference Vectors (Requirement 3.5)
// ============================================================================
//
// These tests compare PoseidonGoldilocks::permute() output against every
// hardcoded reference test vector. They fail the build if any vector diverges.

#[test]
fn test_conformance_all_reference_vectors() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    assert!(
        vectors.len() >= 20,
        "Must have at least 20 reference vectors, got {}",
        vectors.len()
    );

    for (name, input, expected) in &vectors {
        let mut state = state_from(input);
        poseidon.permute(&mut state);
        let actual = state_to_u64(&state);

        assert_eq!(
            &actual, expected,
            "Reference vector '{}' DIVERGED!\n  Input:    {:?}\n  Expected: {:?}\n  Actual:   {:?}",
            name, input, expected, actual
        );
    }
}

// Individual conformance tests for each category — these provide more
// granular failure reporting than the single combined test above.

#[test]
fn test_conformance_zero_state() {
    let poseidon = PoseidonGoldilocks::new();
    let mut state = [GoldilocksField::ZERO; STATE_WIDTH];
    poseidon.permute(&mut state);
    let actual = state_to_u64(&state);
    let expected = [17776268160436713992, 13484960287237122879, 8072290751062992204, 11580099673436387810, 10497940406619895323, 2228943300489664845, 17631245483957960459, 8588595693792710836, 594294450056788254, 5771626098660422165, 7799099188971467012, 4378146451967639013];
    assert_eq!(actual, expected, "Zero state permutation diverged");
}

#[test]
fn test_conformance_single_nonzero_elements() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    for (name, input, expected) in &vectors {
        if name.starts_with("single_elem") {
            let mut state = state_from(input);
            poseidon.permute(&mut state);
            let actual = state_to_u64(&state);
            assert_eq!(
                &actual, expected,
                "Single non-zero element vector '{}' diverged",
                name
            );
        }
    }
}

#[test]
fn test_conformance_all_ones() {
    let poseidon = PoseidonGoldilocks::new();
    let mut state = state_from(&[1; STATE_WIDTH]);
    poseidon.permute(&mut state);
    let actual = state_to_u64(&state);
    let expected = [16876301287218863540, 10221470712347406754, 523441862593599623, 648224604478182890, 3685777650489960684, 6069221330454559794, 4230991806330459835, 8019351987677262943, 9493510694639742092, 13317897876414229300, 8822892940058747718, 18033018322883919080];
    assert_eq!(actual, expected, "All-ones state permutation diverged");
}

#[test]
fn test_conformance_all_max() {
    let poseidon = PoseidonGoldilocks::new();
    let mut state = state_from(&[P - 1; STATE_WIDTH]);
    poseidon.permute(&mut state);
    let actual = state_to_u64(&state);
    let expected = [3492001120930797373, 3341881054653038042, 4090369161410131700, 11000346046292789094, 16730027019263958247, 582892198737888034, 8071762114649879955, 15843383151331995084, 13636269320184716572, 1507585169200131264, 2291558161465885179, 13951554099820012272];
    assert_eq!(actual, expected, "All-max state permutation diverged");
}

#[test]
fn test_conformance_sequential_states() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    for (name, input, expected) in &vectors {
        if name.starts_with("sequential") {
            let mut state = state_from(input);
            poseidon.permute(&mut state);
            let actual = state_to_u64(&state);
            assert_eq!(
                &actual, expected,
                "Sequential vector '{}' diverged",
                name
            );
        }
    }
}

#[test]
fn test_conformance_random_states() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    for (name, input, expected) in &vectors {
        if name.starts_with("random_") || name.starts_with("powers_") || name.starts_with("fibonacci") || name.starts_with("alternating") {
            let mut state = state_from(input);
            poseidon.permute(&mut state);
            let actual = state_to_u64(&state);
            assert_eq!(
                &actual, expected,
                "Random vector '{}' diverged",
                name
            );
        }
    }
}

/// Verify all reference vector outputs are in the canonical field range [0, p).
#[test]
fn test_reference_vectors_output_in_field() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    for (name, input, _) in &vectors {
        let mut state = state_from(input);
        poseidon.permute(&mut state);
        for (i, elem) in state.iter().enumerate() {
            assert!(
                elem.0 < GoldilocksField::MODULUS,
                "Vector '{}': output[{}] = {} is not in field [0, p)",
                name, i, elem.0
            );
        }
    }
}

/// Verify determinism: running permute() twice on the same input produces
/// identical output for every reference vector.
#[test]
fn test_reference_vectors_deterministic() {
    let poseidon = PoseidonGoldilocks::new();
    let vectors = reference_vectors();

    for (name, input, _) in &vectors {
        let mut state1 = state_from(input);
        let mut state2 = state_from(input);
        poseidon.permute(&mut state1);
        poseidon.permute(&mut state2);
        assert_eq!(
            state1, state2,
            "Vector '{}': permute() is not deterministic",
            name
        );
    }
}

/// Verify that the reference vector count meets the minimum requirement.
#[test]
fn test_minimum_reference_vector_count() {
    let vectors = reference_vectors();
    assert!(
        vectors.len() >= 20,
        "Requirement 3.2: must have at least 20 reference vectors, got {}",
        vectors.len()
    );
}

// ============================================================================
// Task 3.2: MDS Matrix Non-Singularity Verification (Requirement 3.4)
// ============================================================================
//
// The MDS property requires that every square submatrix of the 12×12 Cauchy
// matrix is non-singular over the Goldilocks field. We verify this by:
// 1. Constructing the MDS matrix with x_i = i+1, y_j = 12+j+1
// 2. Enumerating all square submatrices for sizes 1 through 12
// 3. Computing determinants over the Goldilocks field
// 4. Asserting all determinants are non-zero
//
// Total submatrices: sum_{k=1}^{12} C(12,k)^2 = 4,083,150 + 1 (full matrix)
// This is computationally feasible as a one-time test.

/// Generate the 12×12 Cauchy MDS matrix with x_i = i+1, y_j = 12+j+1.
fn generate_mds_matrix() -> [[GoldilocksField; 12]; 12] {
    let mut matrix = [[GoldilocksField::ZERO; 12]; 12];
    for i in 0..12 {
        for j in 0..12 {
            let x_i = GoldilocksField((i + 1) as u64);
            let y_j = GoldilocksField((12 + j + 1) as u64);
            let sum = x_i.add(y_j);
            matrix[i][j] = sum.inv().expect("MDS Cauchy matrix: sum must be non-zero");
        }
    }
    matrix
}

/// Compute the determinant of a square matrix over GoldilocksField using
/// Gaussian elimination with partial pivoting.
fn determinant(matrix: &[Vec<GoldilocksField>]) -> GoldilocksField {
    let n = matrix.len();
    if n == 0 {
        return GoldilocksField::ONE;
    }
    if n == 1 {
        return matrix[0][0];
    }

    // Work on a mutable copy
    let mut m: Vec<Vec<GoldilocksField>> = matrix.to_vec();
    let mut det = GoldilocksField::ONE;

    for col in 0..n {
        // Find pivot (first non-zero in column)
        let mut pivot_row = None;
        for row in col..n {
            if m[row][col] != GoldilocksField::ZERO {
                pivot_row = Some(row);
                break;
            }
        }

        let pivot_row = match pivot_row {
            Some(r) => r,
            None => return GoldilocksField::ZERO, // Singular
        };

        // Swap rows if needed
        if pivot_row != col {
            m.swap(col, pivot_row);
            // Swapping rows negates the determinant: multiply by (p-1) = -1
            det = det.mul(GoldilocksField(GoldilocksField::MODULUS - 1));
        }

        let pivot = m[col][col];
        det = det.mul(pivot);

        // Eliminate below
        let pivot_inv = pivot.inv().expect("pivot is non-zero");
        for row in (col + 1)..n {
            let factor = m[row][col].mul(pivot_inv);
            m[row][col] = GoldilocksField::ZERO;
            for j in (col + 1)..n {
                let sub_val = factor.mul(m[col][j]);
                m[row][j] = m[row][j].sub(sub_val);
            }
        }
    }

    det
}

/// Extract a submatrix given row and column index sets.
fn extract_submatrix(
    matrix: &[[GoldilocksField; 12]; 12],
    rows: &[usize],
    cols: &[usize],
) -> Vec<Vec<GoldilocksField>> {
    rows.iter()
        .map(|&r| cols.iter().map(|&c| matrix[r][c]).collect())
        .collect()
}

/// Generate all combinations of `k` elements from `0..n`.
fn combinations(n: usize, k: usize) -> Vec<Vec<usize>> {
    let mut result = Vec::new();
    let mut combo = vec![0usize; k];

    fn generate(combo: &mut Vec<usize>, start: usize, n: usize, k: usize, pos: usize, result: &mut Vec<Vec<usize>>) {
        if pos == k {
            result.push(combo.clone());
            return;
        }
        for i in start..=(n - k + pos) {
            combo[pos] = i;
            generate(combo, i + 1, n, k, pos + 1, result);
        }
    }

    generate(&mut combo, 0, n, k, 0, &mut result);
    result
}

/// Verify that every square submatrix of the 12×12 Cauchy MDS matrix is
/// non-singular over the Goldilocks field.
///
/// This is the definitive MDS property check: a matrix is MDS if and only if
/// every square submatrix has non-zero determinant.
///
/// Requirements: 3.4
#[test]
fn test_mds_matrix_all_square_submatrices_nonsingular() {
    let mds = generate_mds_matrix();
    let mut total_checked = 0u64;
    let mut singular_found = Vec::new();

    for k in 1..=12usize {
        let row_combos = combinations(12, k);
        let col_combos = combinations(12, k);

        for rows in &row_combos {
            for cols in &col_combos {
                let sub = extract_submatrix(&mds, rows, cols);
                let det = determinant(&sub);
                total_checked += 1;

                if det == GoldilocksField::ZERO {
                    singular_found.push((k, rows.clone(), cols.clone()));
                }
            }
        }
    }

    assert!(
        singular_found.is_empty(),
        "MDS property VIOLATED: found {} singular submatrices out of {} checked.\n\
         First singular submatrix: size={}, rows={:?}, cols={:?}",
        singular_found.len(),
        total_checked,
        singular_found[0].0,
        singular_found[0].1,
        singular_found[0].2,
    );

    // Verify we checked the expected number of submatrices
    // sum_{k=1}^{12} C(12,k)^2
    let expected_count: u64 = (1..=12u64)
        .map(|k| {
            let c = combinations(12, k as usize).len() as u64;
            c * c
        })
        .sum();
    assert_eq!(
        total_checked, expected_count,
        "Expected to check {} submatrices, checked {}",
        expected_count, total_checked
    );

    println!(
        "MDS property verified: all {} square submatrices are non-singular",
        total_checked
    );
}

/// Verify the full 12×12 MDS matrix determinant is non-zero.
#[test]
fn test_mds_full_matrix_nonsingular() {
    let mds = generate_mds_matrix();
    let full: Vec<Vec<GoldilocksField>> = (0..12)
        .map(|i| mds[i].to_vec())
        .collect();
    let det = determinant(&full);
    assert_ne!(
        det,
        GoldilocksField::ZERO,
        "Full 12×12 MDS matrix must be non-singular"
    );
}

/// Verify MDS matrix entries match the Cauchy construction formula.
#[test]
fn test_mds_matrix_cauchy_construction() {
    let mds = generate_mds_matrix();
    for i in 0..12 {
        for j in 0..12 {
            let x_i = GoldilocksField((i + 1) as u64);
            let y_j = GoldilocksField((12 + j + 1) as u64);
            let expected = x_i.add(y_j).inv().unwrap();
            assert_eq!(
                mds[i][j], expected,
                "MDS[{}][{}] does not match Cauchy formula 1/(x_i + y_j)",
                i, j
            );
        }
    }
}

/// Verify all MDS matrix entries are non-zero.
#[test]
fn test_mds_matrix_all_entries_nonzero() {
    let mds = generate_mds_matrix();
    for i in 0..12 {
        for j in 0..12 {
            assert_ne!(
                mds[i][j],
                GoldilocksField::ZERO,
                "MDS[{}][{}] must be non-zero",
                i, j
            );
        }
    }
}

/// Verify MDS matrix is deterministic across multiple generations.
#[test]
fn test_mds_matrix_deterministic() {
    let mds1 = generate_mds_matrix();
    let mds2 = generate_mds_matrix();
    for i in 0..12 {
        for j in 0..12 {
            assert_eq!(
                mds1[i][j], mds2[i][j],
                "MDS matrix generation is not deterministic at [{},{}]",
                i, j
            );
        }
    }
}
