[package]
name = "vsel_reference_state_machine_exec"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.16.0"

[dependencies]
cairo_execute = "2.16.0"
vsel_reference_state_machine_core = { path = "../semantic_core" }

[[target.executable]]

[cairo]
enable-gas = false
