[package]
name = "vsel-mapping"
version = "0.1.0"
edition = "2021"

[dependencies]
vsel-core = { path = "../vsel-core" }
vsel-sir = { path = "../vsel-sir" }
vsel-trace = { path = "../vsel-trace" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
