//! SIR/IR deserialization from JSON.
//!
//! Derived from: Requirement 9.7 — the SIR/IR derivation pipeline.
//!
//! Reads JSON-formatted IR files generated by Lean 4 export tooling and
//! produces typed `SirProgram` values consumed by the execution engine
//! and constraint compiler.

use crate::types::*;

/// Errors that can occur during SIR deserialization.
#[derive(Debug, thiserror::Error)]
pub enum DeserializeError {
    /// JSON parsing or structural error.
    #[error("JSON deserialization error: {0}")]
    Json(#[from] serde_json::Error),

    /// Semantic validation error after successful parsing.
    #[error("SIR validation error: {0}")]
    Validation(String),
}

/// Deserialize a `SirProgram` from a JSON string.
pub fn deserialize_program(json: &str) -> Result<SirProgram, DeserializeError> {
    let program: SirProgram = serde_json::from_str(json)?;
    validate_program(&program)?;
    Ok(program)
}

/// Deserialize a `SirProgram` from a JSON byte slice.
pub fn deserialize_program_from_bytes(bytes: &[u8]) -> Result<SirProgram, DeserializeError> {
    let program: SirProgram = serde_json::from_slice(bytes)?;
    validate_program(&program)?;
    Ok(program)
}

/// Deserialize a single `SirExpr` from a JSON string (useful for testing).
pub fn deserialize_expr(json: &str) -> Result<SirExpr, DeserializeError> {
    let expr: SirExpr = serde_json::from_str(json)?;
    Ok(expr)
}

/// Deserialize a single `SirValue` from a JSON string (useful for testing).
pub fn deserialize_value(json: &str) -> Result<SirValue, DeserializeError> {
    let value: SirValue = serde_json::from_str(json)?;
    Ok(value)
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// Validate structural invariants of a deserialized SIR program.
fn validate_program(program: &SirProgram) -> Result<(), DeserializeError> {
    if program.version.is_empty() {
        return Err(DeserializeError::Validation(
            "SIR program version must not be empty".into(),
        ));
    }

    for t in &program.transitions {
        if t.name.is_empty() {
            return Err(DeserializeError::Validation(
                "transition name must not be empty".into(),
            ));
        }
        if t.class.is_empty() {
            return Err(DeserializeError::Validation(format!(
                "transition '{}' has empty class",
                t.name
            )));
        }
    }

    for inv in &program.invariants {
        if inv.name.is_empty() {
            return Err(DeserializeError::Validation(
                "invariant name must not be empty".into(),
            ));
        }
        if inv.category.is_empty() {
            return Err(DeserializeError::Validation(format!(
                "invariant '{}' has empty category",
                inv.name
            )));
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal valid SIR program JSON.
    fn minimal_program_json() -> String {
        r#"{
            "version": "0.1.0",
            "state_schema": { "fields": [{"name": "balance", "field_type": "Int"}] },
            "input_schema": { "fields": [{"name": "amount", "field_type": "Int"}] },
            "transitions": [
                {
                    "name": "deposit",
                    "class": "Update",
                    "preconditions": [],
                    "postconditions": [],
                    "body": {"kind": "Var", "name": "state"},
                    "allowed_mutations": ["balance"]
                }
            ],
            "invariants": [
                {
                    "name": "L_cons",
                    "category": "local",
                    "expr": {"kind": "Literal", "value": {"type": "Bool", "value": true}}
                }
            ],
            "observables": []
        }"#
        .to_string()
    }

    #[test]
    fn test_deserialize_minimal_program() {
        let program = deserialize_program(&minimal_program_json()).unwrap();
        assert_eq!(program.version, "0.1.0");
        assert_eq!(program.transitions.len(), 1);
        assert_eq!(program.transitions[0].name, "deposit");
        assert_eq!(program.transitions[0].class, "Update");
        assert_eq!(program.invariants.len(), 1);
        assert_eq!(program.invariants[0].name, "L_cons");
    }

    #[test]
    fn test_deserialize_program_from_bytes() {
        let bytes = minimal_program_json().into_bytes();
        let program = deserialize_program_from_bytes(&bytes).unwrap();
        assert_eq!(program.version, "0.1.0");
    }

    #[test]
    fn test_deserialize_invalid_json() {
        let result = deserialize_program("not json");
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), DeserializeError::Json(_)));
    }

    #[test]
    fn test_deserialize_empty_version_fails_validation() {
        let json = r#"{
            "version": "",
            "state_schema": { "fields": [] },
            "input_schema": { "fields": [] },
            "transitions": [],
            "invariants": [],
            "observables": []
        }"#;
        let result = deserialize_program(json);
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            DeserializeError::Validation(_)
        ));
    }

    #[test]
    fn test_deserialize_empty_transition_name_fails() {
        let json = r#"{
            "version": "0.1.0",
            "state_schema": { "fields": [] },
            "input_schema": { "fields": [] },
            "transitions": [
                {
                    "name": "",
                    "class": "Update",
                    "preconditions": [],
                    "postconditions": [],
                    "body": {"kind": "Literal", "value": {"type": "Unit"}},
                    "allowed_mutations": []
                }
            ],
            "invariants": [],
            "observables": []
        }"#;
        let result = deserialize_program(json);
        assert!(result.is_err());
    }

    #[test]
    fn test_deserialize_empty_invariant_category_fails() {
        let json = r#"{
            "version": "0.1.0",
            "state_schema": { "fields": [] },
            "input_schema": { "fields": [] },
            "transitions": [],
            "invariants": [
                {
                    "name": "test_inv",
                    "category": "",
                    "expr": {"kind": "Literal", "value": {"type": "Bool", "value": true}}
                }
            ],
            "observables": []
        }"#;
        let result = deserialize_program(json);
        assert!(result.is_err());
    }

    #[test]
    fn test_deserialize_expr_literal() {
        let json = r#"{"kind": "Literal", "value": {"type": "Int", "value": 42}}"#;
        let expr = deserialize_expr(json).unwrap();
        assert_eq!(
            expr,
            SirExpr::Literal {
                value: SirValue::Int { value: 42 }
            }
        );
    }

    #[test]
    fn test_deserialize_expr_binop() {
        let json = r#"{
            "kind": "BinOp",
            "op": "add",
            "left": {"kind": "Var", "name": "x"},
            "right": {"kind": "Literal", "value": {"type": "Int", "value": 1}}
        }"#;
        let expr = deserialize_expr(json).unwrap();
        assert_eq!(
            expr,
            SirExpr::BinOp {
                op: "add".into(),
                left: Box::new(SirExpr::Var { name: "x".into() }),
                right: Box::new(SirExpr::Literal {
                    value: SirValue::Int { value: 1 }
                }),
            }
        );
    }

    #[test]
    fn test_deserialize_expr_let() {
        let json = r#"{
            "kind": "Let",
            "name": "y",
            "value": {"kind": "Literal", "value": {"type": "Int", "value": 10}},
            "body": {"kind": "Var", "name": "y"}
        }"#;
        let expr = deserialize_expr(json).unwrap();
        assert_eq!(
            expr,
            SirExpr::Let {
                name: "y".into(),
                value: Box::new(SirExpr::Literal {
                    value: SirValue::Int { value: 10 }
                }),
                body: Box::new(SirExpr::Var { name: "y".into() }),
            }
        );
    }

    #[test]
    fn test_deserialize_value_bytes() {
        let json = r#"{"type": "Bytes", "value": [1, 2, 3]}"#;
        let v = deserialize_value(json).unwrap();
        assert_eq!(
            v,
            SirValue::Bytes {
                value: vec![1, 2, 3]
            }
        );
    }

    #[test]
    fn test_deserialize_value_tuple() {
        let json = r#"{"type": "Tuple", "elements": [{"type": "Int", "value": 1}, {"type": "Bool", "value": false}]}"#;
        let v = deserialize_value(json).unwrap();
        assert_eq!(
            v,
            SirValue::Tuple {
                elements: vec![SirValue::Int { value: 1 }, SirValue::Bool { value: false },]
            }
        );
    }

    #[test]
    fn test_deserialize_program_with_observables() {
        let json = r#"{
            "version": "0.1.0",
            "state_schema": { "fields": [] },
            "input_schema": { "fields": [] },
            "transitions": [],
            "invariants": [],
            "observables": [
                {
                    "name": "total_balance",
                    "expr": {"kind": "Var", "name": "state"}
                }
            ]
        }"#;
        let program = deserialize_program(json).unwrap();
        assert_eq!(program.observables.len(), 1);
        assert_eq!(program.observables[0].name, "total_balance");
    }

    #[test]
    fn test_deserialize_nested_expr() {
        let json = r#"{
            "kind": "If",
            "cond": {
                "kind": "BinOp",
                "op": "gt",
                "left": {"kind": "FieldAccess", "expr": {"kind": "Var", "name": "state"}, "field": "balance"},
                "right": {"kind": "Literal", "value": {"type": "Int", "value": 0}}
            },
            "then_": {"kind": "Literal", "value": {"type": "Bool", "value": true}},
            "else_": {"kind": "Literal", "value": {"type": "Bool", "value": false}}
        }"#;
        let expr = deserialize_expr(json).unwrap();
        match expr {
            SirExpr::If { cond, .. } => match *cond {
                SirExpr::BinOp { op, .. } => assert_eq!(op, "gt"),
                other => panic!("expected BinOp, got {:?}", other),
            },
            other => panic!("expected If, got {:?}", other),
        }
    }

    // -----------------------------------------------------------------------
    // Example IR artifact deserialization tests (sir/examples/)
    // Validates that export tooling output is consumable by Rust.
    // Requirement: 9.7
    // -----------------------------------------------------------------------

    #[test]
    fn test_deserialize_example_full_program() {
        let json = include_str!("../../../../sir/examples/full_program.json");
        let program = deserialize_program(json).unwrap();
        assert_eq!(program.version, "0.1.0");
        assert_eq!(program.state_schema.fields.len(), 3);
        assert_eq!(program.input_schema.fields.len(), 3);
        assert_eq!(program.transitions.len(), 3);
        assert_eq!(program.transitions[0].name, "genesis");
        assert_eq!(program.transitions[0].class, "Init");
        assert_eq!(program.transitions[1].name, "deposit");
        assert_eq!(program.transitions[1].class, "Update");
        assert_eq!(program.transitions[2].name, "withdraw");
        assert_eq!(program.transitions[2].class, "Update");
        assert_eq!(program.invariants.len(), 3);
        assert_eq!(program.observables.len(), 1);
    }

    #[test]
    fn test_deserialize_example_update_transition() {
        let json = include_str!("../../../../sir/examples/update_transition.json");
        let transition: SirTransition = serde_json::from_str(json).unwrap();
        assert_eq!(transition.name, "deposit");
        assert_eq!(transition.class, "Update");
        assert_eq!(transition.preconditions.len(), 1);
        assert_eq!(transition.postconditions.len(), 1);
        assert_eq!(transition.allowed_mutations, vec!["balance"]);
    }

    #[test]
    fn test_deserialize_example_init_transition() {
        let json = include_str!("../../../../sir/examples/init_transition.json");
        let transition: SirTransition = serde_json::from_str(json).unwrap();
        assert_eq!(transition.name, "genesis");
        assert_eq!(transition.class, "Init");
        assert!(transition.preconditions.is_empty());
        assert_eq!(transition.postconditions.len(), 2);
        assert_eq!(transition.allowed_mutations.len(), 3);
    }

    #[test]
    fn test_deserialize_example_invariants() {
        let json = include_str!("../../../../sir/examples/invariants.json");
        let invariants: Vec<SirInvariant> = serde_json::from_str(json).unwrap();
        assert_eq!(invariants.len(), 4);
        assert_eq!(invariants[0].name, "L_cons");
        assert_eq!(invariants[0].category, "local");
        assert_eq!(invariants[1].name, "G_valid");
        assert_eq!(invariants[1].category, "global");
        assert_eq!(invariants[2].name, "G_solvency");
        assert_eq!(invariants[2].category, "global");
        assert_eq!(invariants[3].name, "E_cost");
        assert_eq!(invariants[3].category, "economic");
    }

    #[test]
    fn test_example_full_program_deterministic_reserialization() {
        // Verify CONST-4: deserialize then re-serialize produces identical JSON
        let json = include_str!("../../../../sir/examples/full_program.json");
        let program: SirProgram = serde_json::from_str(json).unwrap();
        let reserialized = serde_json::to_string_pretty(&program).unwrap();
        let program2: SirProgram = serde_json::from_str(&reserialized).unwrap();
        assert_eq!(program, program2);
    }
}
