//! SIR type definitions — deserialized from JSON generated by Lean 4 tooling.
//!
//! Derived from: REFINEMENT_STRATEGY.md, TECH_SPEC.md, design.md Component 10.
//!
//! SIR (Semantic Intermediate Representation) is the typed, deterministic bridge
//! between Lean 4 formal specification and Rust concrete execution. It is generated
//! by tooling — never hand-written.

use serde::Deserialize;
use std::collections::BTreeMap;

// ---------------------------------------------------------------------------
// SIR values — runtime values in the SIR interpreter
// ---------------------------------------------------------------------------

/// Runtime value in the SIR interpreter.
#[derive(Clone, Debug, PartialEq, Deserialize)]
#[serde(tag = "type")]
pub enum SirValue {
    /// Integer value (i64 for signed arithmetic).
    Int { value: i64 },
    /// Boolean value.
    Bool { value: bool },
    /// Byte array value.
    Bytes { value: Vec<u8> },
    /// Ordered list of values.
    List { elements: Vec<SirValue> },
    /// Ordered map of string keys to values.
    Map { entries: BTreeMap<String, SirValue> },
    /// Tuple of values.
    Tuple { elements: Vec<SirValue> },
    /// Unit / void value.
    Unit,
}

// ---------------------------------------------------------------------------
// SIR expressions — the AST
// ---------------------------------------------------------------------------

/// SIR expression AST node — typed, deterministic.
///
/// Tagged union deserialized from JSON with `"kind"` discriminator.
#[derive(Clone, Debug, PartialEq, Deserialize)]
#[serde(tag = "kind")]
pub enum SirExpr {
    /// Literal value.
    Literal { value: SirValue },
    /// Variable reference.
    Var { name: String },
    /// Function application.
    Apply {
        func: Box<SirExpr>,
        args: Vec<SirExpr>,
    },
    /// Let binding.
    Let {
        name: String,
        value: Box<SirExpr>,
        body: Box<SirExpr>,
    },
    /// Conditional expression.
    If {
        cond: Box<SirExpr>,
        then_: Box<SirExpr>,
        else_: Box<SirExpr>,
    },
    /// Pattern match.
    Match {
        scrutinee: Box<SirExpr>,
        arms: Vec<SirMatchArm>,
    },
    /// Field access on a map/record value.
    FieldAccess { expr: Box<SirExpr>, field: String },
    /// Binary operation.
    BinOp {
        op: String,
        left: Box<SirExpr>,
        right: Box<SirExpr>,
    },
}

/// A single arm in a `Match` expression.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirMatchArm {
    /// Pattern to match — for now a literal value or wildcard name.
    pub pattern: SirPattern,
    /// Body expression evaluated when the pattern matches.
    pub body: SirExpr,
}

/// Pattern in a match arm.
#[derive(Clone, Debug, PartialEq, Deserialize)]
#[serde(tag = "kind")]
pub enum SirPattern {
    /// Match a literal value.
    Literal { value: SirValue },
    /// Bind the scrutinee to a variable name (wildcard).
    Var { name: String },
}

// ---------------------------------------------------------------------------
// SIR schema types
// ---------------------------------------------------------------------------

/// Schema for a single field in state or input.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirFieldSchema {
    pub name: String,
    pub field_type: String,
}

/// Schema describing the shape of the state.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirStateSchema {
    pub fields: Vec<SirFieldSchema>,
}

/// Schema describing the shape of an input.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirInputSchema {
    pub fields: Vec<SirFieldSchema>,
}

/// Schema describing an observable output.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirObservable {
    pub name: String,
    pub expr: SirExpr,
}

// ---------------------------------------------------------------------------
// SIR top-level structures
// ---------------------------------------------------------------------------

/// A single transition definition in the SIR program.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirTransition {
    /// Transition name (e.g. "transfer", "deposit").
    pub name: String,
    /// Transition class (e.g. "Update", "Init").
    pub class: String,
    /// Guard / precondition expressions — all must hold for the transition to fire.
    pub preconditions: Vec<SirExpr>,
    /// Postcondition expressions — all must hold after the transition.
    pub postconditions: Vec<SirExpr>,
    /// Transition body — the expression that computes the new state.
    pub body: SirExpr,
    /// Fields the transition is allowed to mutate.
    pub allowed_mutations: Vec<String>,
}

/// An invariant definition in the SIR program.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirInvariant {
    /// Invariant name (e.g. "L_cons", "G_solvency").
    pub name: String,
    /// Invariant category (e.g. "local", "global", "temporal", "economic").
    pub category: String,
    /// The invariant expression — must evaluate to `Bool { value: true }`.
    pub expr: SirExpr,
}

/// Top-level SIR program — deserialized from JSON generated by Lean 4 tooling.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct SirProgram {
    /// SIR schema version.
    pub version: String,
    /// State schema describing the shape of the state.
    pub state_schema: SirStateSchema,
    /// Input schema describing the shape of inputs.
    pub input_schema: SirInputSchema,
    /// Transition definitions.
    pub transitions: Vec<SirTransition>,
    /// Invariant definitions.
    pub invariants: Vec<SirInvariant>,
    /// Observable definitions.
    pub observables: Vec<SirObservable>,
}

// ---------------------------------------------------------------------------
// Interpreter environment
// ---------------------------------------------------------------------------

/// Environment for the SIR interpreter — maps variable names to values.
#[derive(Clone, Debug, PartialEq)]
pub struct SirEnv {
    pub bindings: BTreeMap<String, SirValue>,
}

impl SirEnv {
    /// Create an empty environment.
    pub fn new() -> Self {
        Self {
            bindings: BTreeMap::new(),
        }
    }

    /// Look up a variable.
    pub fn get(&self, name: &str) -> Option<&SirValue> {
        self.bindings.get(name)
    }

    /// Extend the environment with a new binding, returning a new env.
    pub fn extend(&self, name: String, value: SirValue) -> Self {
        let mut bindings = self.bindings.clone();
        bindings.insert(name, value);
        Self { bindings }
    }
}

impl Default for SirEnv {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sir_value_int_deserialize() {
        let json = r#"{"type": "Int", "value": 42}"#;
        let v: SirValue = serde_json::from_str(json).unwrap();
        assert_eq!(v, SirValue::Int { value: 42 });
    }

    #[test]
    fn test_sir_value_bool_deserialize() {
        let json = r#"{"type": "Bool", "value": true}"#;
        let v: SirValue = serde_json::from_str(json).unwrap();
        assert_eq!(v, SirValue::Bool { value: true });
    }

    #[test]
    fn test_sir_value_unit_deserialize() {
        let json = r#"{"type": "Unit"}"#;
        let v: SirValue = serde_json::from_str(json).unwrap();
        assert_eq!(v, SirValue::Unit);
    }

    #[test]
    fn test_sir_value_list_deserialize() {
        let json = r#"{"type": "List", "elements": [{"type": "Int", "value": 1}, {"type": "Int", "value": 2}]}"#;
        let v: SirValue = serde_json::from_str(json).unwrap();
        assert_eq!(
            v,
            SirValue::List {
                elements: vec![SirValue::Int { value: 1 }, SirValue::Int { value: 2 }]
            }
        );
    }

    #[test]
    fn test_sir_value_map_deserialize() {
        let json = r#"{"type": "Map", "entries": {"x": {"type": "Int", "value": 10}}}"#;
        let v: SirValue = serde_json::from_str(json).unwrap();
        let mut expected = BTreeMap::new();
        expected.insert("x".to_string(), SirValue::Int { value: 10 });
        assert_eq!(v, SirValue::Map { entries: expected });
    }

    #[test]
    fn test_sir_expr_literal_deserialize() {
        let json = r#"{"kind": "Literal", "value": {"type": "Int", "value": 99}}"#;
        let e: SirExpr = serde_json::from_str(json).unwrap();
        assert_eq!(
            e,
            SirExpr::Literal {
                value: SirValue::Int { value: 99 }
            }
        );
    }

    #[test]
    fn test_sir_expr_var_deserialize() {
        let json = r#"{"kind": "Var", "name": "x"}"#;
        let e: SirExpr = serde_json::from_str(json).unwrap();
        assert_eq!(e, SirExpr::Var { name: "x".into() });
    }

    #[test]
    fn test_sir_expr_if_deserialize() {
        let json = r#"{
            "kind": "If",
            "cond": {"kind": "Var", "name": "flag"},
            "then_": {"kind": "Literal", "value": {"type": "Int", "value": 1}},
            "else_": {"kind": "Literal", "value": {"type": "Int", "value": 0}}
        }"#;
        let e: SirExpr = serde_json::from_str(json).unwrap();
        assert_eq!(
            e,
            SirExpr::If {
                cond: Box::new(SirExpr::Var { name: "flag".into() }),
                then_: Box::new(SirExpr::Literal {
                    value: SirValue::Int { value: 1 }
                }),
                else_: Box::new(SirExpr::Literal {
                    value: SirValue::Int { value: 0 }
                }),
            }
        );
    }

    #[test]
    fn test_sir_env_extend_and_get() {
        let env = SirEnv::new();
        let env2 = env.extend("x".into(), SirValue::Int { value: 42 });
        assert_eq!(env2.get("x"), Some(&SirValue::Int { value: 42 }));
        assert_eq!(env2.get("y"), None);
    }

    #[test]
    fn test_sir_env_extend_shadows() {
        let env = SirEnv::new()
            .extend("x".into(), SirValue::Int { value: 1 })
            .extend("x".into(), SirValue::Int { value: 2 });
        assert_eq!(env.get("x"), Some(&SirValue::Int { value: 2 }));
    }
}
